#!/usr/bin/bash
#SBATCH -p part1
#SBATCH -J spinup
#SBATCH -n 60
#SBATCH --output=spinup.log

 
MAINDIR=/ceaza/lucas/CROCO-CEAZAMAR
SCRATCHDIR=${MAINDIR}/HINDCAST/OUTPUT
OUTPUTDIR=${MAINDIR}/HINDCAST/OUTPUT
CROCOEXEC=${MAINDIR}/HINDCAST/croco